Fix asdf bug and add oci command line.

diff --git a/.zsh/functions/asdf-ensure-available b/.zsh/functions/asdf-ensure-available
--- a/.zsh/functions/asdf-ensure-available
+++ b/.zsh/functions/asdf-ensure-available
@@ -3,22 +3,24 @@
 
 for shortname version in "${@}" ; do
 
-    if [[ ! -d ${ASDF_DATA_DIR}/plugins/$shortname ]] ; then
+    # As of 2024-04-11, there's a bug somewhere that prevents these asdf plugins from working on my m2 mac.
+    # They can't find _any_ versions.  There and there only, use system versions
+    if [[ $OSTYPE == darwin* && ($shortname == helm || $shortname == stern ) ]] ; then
+        asdf global $shortname system
+        #echo "Skipping install of ${shortname} because of bug, using system version..." >&2
+        continue
+    fi
+
+    if [[ ! -d ${ASDF_DATA_DIR}/installs/$shortname/$version ]] ; then
         green "asdf-installing ${shortname}..." >&2
         asdf plugin add $shortname
 
-
-        # As of 2024-04-11, there's a bug somewhere that prevents these asdf plugins from working on my m2 mac.
-        # They can't find _any_ versions.  There and there only, use system versions
-        if [[ $OSTYPE == darwin* && ($shortname == helm || $shortname == stern ) ]] ; then
-            asdf global $shortname system
-            echo "Skipping install of ${shortname} because of bug, using system version..." >&2
-
-        else
-            asdf install $shortname $version
-            asdf global $shortname $version
+        asdf install $shortname $version
+        if [[ $? != 0 ]] ; then
+            echo "Error installing $shortname at $version" >&2
+            rm -fr ${ASDF_DATA_DIR}/installs/$shortname/$version
         fi
-
+        asdf global $shortname $version
     fi
 
 done
