Fixes for Centos 7.9.2009 and BMC-specific plugin source.

diff --git a/.zsh/functions/cached-eval b/.zsh/functions/cached-eval
--- a/.zsh/functions/cached-eval
+++ b/.zsh/functions/cached-eval
@@ -9,7 +9,13 @@ fi
 if [[ ! -e "${filename}" ]] ; then
     echo "cached-eval: Generating cache for ${argv[*]}" >&2
     "${argv[@]}" > ${filename}
+
+    if [[ $? -ne 0 ]] ; then
+        echo "cached-eval: command failed: ${argv[*]}" >&2
+        rm -f "${filename}"
+        return 2
+    fi
 fi
-eval "$(< ${filename} )"
+source "${filename}"
 
 # vim: set ft=zsh:
